tools:
    php_mess_detector:
        enabled:                true
        filter:
            excluded_paths:
                - 'vendor/*'
    php_cpd:
        enabled:                true
        excluded_dirs:
            - 'vendor'
    php_pdepend:
        enabled:                true
        excluded_dirs:
            - vendor
    php_cs_fixer:
        enabled:                true
        config:
            level:              psr2
        filter:
            excluded_paths:
                - 'vendor/*'
